version: '3'

services:
  panda_db:
    image: mysql:latest    
    container_name: panda_db

    environment:
      MYSQL_DATABASE: panda_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    volumes:
      - pandadata:/var/lib/mysql

  panda_pma:
    image: phpmyadmin/phpmyadmin
    container_name: panda_pma

    environment:
      PMA_HOST: panda_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

    ports:
      - 2200:80

  web:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./webapp/:/usr/webapp

    ports:
      - 5000:5000


volumes:
  pandadata:
  

